version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/plans-microservice
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - HOST=0.0.0.0
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy # <--- ESTA ES LA CLAVE: Espera a que RabbitMQ esté listo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:latest # O la versión que prefieras
    ports:
      - "5672:5672"
      - "15672:15672"
    # Healthcheck para verificar que RabbitMQ realmente responde
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data: